### ISSUE TITLE
Entry won't appear in kickoff when it contains quotes

### ISSUE THREAD

**Issue by erri120** [j0ru/kickoff-dot-desktop#1]
Example output from `kickoff-dot-desktop`:

```txt
Firefox Developer Edition=/usr/lib/firefox-developer-edition/firefox --class="firefoxdeveloperedition"
```

`kickoff` doesn't like the quotes at the end, so this entry won't be parsed and doesn't appear in the list. Replacing `"` with `'` fixes this:

```bash
./kickoff-dot-desktop | tr '"' "'" | kickoff --from-stdin
```

**Comment by j0ru** [comment]
Hey,
this is not really an issue of the `.desktop` parser, but a problem in kickoff.
The problem has already been [noticed](https://github.com/j0ru/kickoff/issues/79), so I'll be closing it here
